name: Generate release artifacts

on:
  release:
    types:
      - created
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.0'
          check-latest: true

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: 'linux/amd64, darwin/amd64'
          package: ''
          name: 'deluge-reannounce'
          compress: 'true'
          dest: 'dist'

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/*

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 